<?php
$title = "Lista de Stocks";
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title);?></h1>
<p>
	( <a href="<?php echo $this->url('stock-rest'); ?>">StocksRest</a> )
</p>


<table class="table">
	<tr>
		<th>Nome</th>
		<th>Sigla</th>
		<th>Vl. Corrrente</th>
		<th>Vl. Abertura</th>
		<th>Vl. Alta</th>
		<th>Vl. Baixa</th>
		<th>Porcentagem</th>
		<th>Volume</th>
		<th>Dt. Atualização</th>
	</tr>
	<?php foreach($stocks as $stock): ?>
	<tr>
		<td><?= $this->escapeHtml($stock->name); ?></td>
		<td><?= $this->escapeHtml($stock->sigla); ?></td>
		<td><?= $this->escapeHtml($stock->current); ?></td>
		<td><?= $this->escapeHtml($stock->open); ?></td>
		<td><?= $this->escapeHtml($stock->high); ?></td>
		<td><?= $this->escapeHtml($stock->low); ?></td>
		<td><?= $this->escapeHtml($stock->percent); ?></td>
		<td><?= $this->escapeHtml($stock->volume); ?></td>
		<td><?= $this->escapeHtml($stock->updatedDate); ?></td>
	</tr>
	<?php endforeach; ?>
</table>