<?php
$title = 'Editar usuário';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
	'user',
	array(
		'action' => 'edit',
		'id'	 => $this->id,
	)
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('mail'));
echo $this->formRow($form->get('reais'));
echo $this->formRow($form->get('dollars'));
echo $this->formRow($form->get('user'));
echo $this->formRow($form->get('password'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();